### PR TITLE
Added new resource on managing secrets in K8s

### PR DESCRIPTION
**Pull request by mariuszmichalowski**

### CODE REVIEW

**Comment by mariuszmichalowski** [comment]
Hey, @vedmichv can you take a look?

**Comment by vedmichv** [comment]
Merged - thanks for update

**Comment by mariuszmichalowski** [comment]
> Merged - thanks for update

Thanks @vedmichv  , I think you accidentally closed this pull request instead of merging:)

**Comment by vedmichv** [comment]
Oh you are right. Now - definitely merged :) 
Also, I'm going to make significant changes for the repo (will do re-certification on start of next year).

**Comment by weisdd** [comment]
@vedmichv just in case, CKS is now running on 1.25 (I think it got upgraded from 1.24 around a week ago), so all references to PSP are obsolete.

**Pull request merged**
